// ══════════════════════════════════════════════
// TYPES
// ══════════════════════════════════════════════
export type Lang    = "fr" | "en" | "es";
export type Tab     = "home" | "documents" | "profile" | "explorer";
export type PhaseId = 1 | 2 | 3 | 4 | 5;

export type PhaseStep = {
  id: string;
  label: Record<Lang, string>;
  desc: Record<Lang, string>;
  urgency: "critical" | "high" | "normal";
  time: number;
  weight: number;
};

// ══════════════════════════════════════════════
// PHASES META
// ══════════════════════════════════════════════
export const PHASES_META: Record<PhaseId, {
  emoji: string;
  name: Record<Lang, string>;
  desc: Record<Lang, string>;
  color: string;
  unlockMsg: Record<Lang, { title: string; msg: string }>;
}> = {
  1: { emoji: "🚀", name: { fr: "Atterrissage",  en: "Landing",       es: "Aterrizaje"   }, desc: { fr: "Tes premières étapes aux USA",      en: "Your first steps in the USA",       es: "Tus primeros pasos en EE.UU."       }, color: "#e8b84b", unlockMsg: { fr: { title: "🚀 Phase 1 complétée !",  msg: "Tu es officiellement installé aux USA. Place aux Fondations !"          }, en: { title: "🚀 Phase 1 complete!",   msg: "You're officially settled. Time to build your Foundations!"             }, es: { title: "🚀 ¡Fase 1 completada!", msg: "¡Estás instalado en EE.UU. A construir las Bases!"                       } } },
  2: { emoji: "🏗️", name: { fr: "Fondations",    en: "Foundations",   es: "Cimientos"    }, desc: { fr: "Construis ta vie financière",        en: "Build your financial life",         es: "Construye tu vida financiera"       }, color: "#2dd4bf", unlockMsg: { fr: { title: "🏗️ Phase 2 complétée !", msg: "Tes fondations sont solides. Place à la Croissance !"                   }, en: { title: "🏗️ Phase 2 complete!",  msg: "Your foundations are solid. Time to Grow!"                             }, es: { title: "🏗️ ¡Fase 2 completada!", msg: "Tus cimientos son sólidos. ¡Es hora de Crecer!"                         } } },
  3: { emoji: "🌱", name: { fr: "Croissance",     en: "Growth",        es: "Crecimiento"  }, desc: { fr: "Développe ton avenir aux USA",       en: "Develop your future in the USA",    es: "Desarrolla tu futuro en EE.UU."    }, color: "#22c55e", unlockMsg: { fr: { title: "🌱 Phase 3 complétée !", msg: "Tu as construit ta vie aux USA. La citoyenneté t'attend !"               }, en: { title: "🌱 Phase 3 complete!",   msg: "You've built your life in the USA. Citizenship awaits!"                 }, es: { title: "🌱 ¡Fase 3 completada!", msg: "Has construido tu vida en EE.UU. ¡La ciudadanía te espera!"              } } },
  4: { emoji: "🇺🇸", name: { fr: "Citoyenneté",   en: "Citizenship",   es: "Ciudadanía"   }, desc: { fr: "Deviens citoyen américain",          en: "Become a US citizen",               es: "Conviértete en ciudadano americano" }, color: "#a78bfa", unlockMsg: { fr: { title: "🇺🇸 Phase 4 complétée !", msg: "Tu es citoyen américain ! Bienvenue dans Kuabo à Vie !"                  }, en: { title: "🇺🇸 Phase 4 complete!",  msg: "You're a US citizen! Welcome to Kuabo for Life!"                        }, es: { title: "🇺🇸 ¡Fase 4 completada!", msg: "¡Eres ciudadano americano! ¡Bienvenido a Kuabo de por Vida!"             } } },
  5: { emoji: "♾️", name: { fr: "Kuabo à Vie",    en: "Kuabo for Life", es: "Kuabo de por Vida" }, desc: { fr: "Rappels et renouvellements à vie", en: "Lifetime reminders and renewals", es: "Recordatorios y renovaciones de por vida" }, color: "#f97316", unlockMsg: { fr: { title: "♾️ Kuabo à Vie !",     msg: "Kuabo sera toujours là pour toi. Pour toujours."                        }, en: { title: "♾️ Kuabo for Life!",     msg: "Kuabo will always be there for you. Forever."                          }, es: { title: "♾️ ¡Kuabo de por Vida!", msg: "Kuabo siempre estará ahí para ti. Para siempre."                        } } },
};

// ══════════════════════════════════════════════
// PHASE STEPS
// ══════════════════════════════════════════════
export const PHASE_STEPS: Record<PhaseId, PhaseStep[]> = {
  1: [
    { id: "ssn",       label: { fr: "Numéro de Sécurité Sociale (SSN)", en: "Social Security Number (SSN)",  es: "Número de Seguro Social (SSN)"  }, desc: { fr: "Obligatoire pour travailler", en: "Required to work",        es: "Obligatorio para trabajar"  }, urgency: "critical", time: 10, weight: 25 },
    { id: "phone",     label: { fr: "Carte SIM / Téléphone US",         en: "SIM Card / US Phone Number",   es: "SIM / Número de teléfono US"    }, desc: { fr: "T-Mobile ou Mint Mobile",    en: "T-Mobile or Mint Mobile",  es: "T-Mobile o Mint Mobile"     }, urgency: "critical", time: 1,  weight: 10 },
    { id: "bank",      label: { fr: "Compte bancaire",                  en: "Bank Account",                 es: "Cuenta bancaria"                }, desc: { fr: "Chase ou Bank of America",   en: "Chase or Bank of America", es: "Chase o Bank of America"    }, urgency: "high",     time: 14, weight: 15 },
    { id: "greencard", label: { fr: "Green Card physique",              en: "Physical Green Card",          es: "Green Card física"              }, desc: { fr: "Courrier USCIS",             en: "USCIS mail",               es: "Correo USCIS"               }, urgency: "high",     time: 21, weight: 10 },
    { id: "housing",   label: { fr: "Logement permanent",               en: "Permanent Housing",            es: "Vivienda permanente"            }, desc: { fr: "Appartement ou maison",      en: "Apartment or house",       es: "Apartamento o casa"         }, urgency: "normal",   time: 30, weight: 15 },
    { id: "job",       label: { fr: "Trouver un emploi",                en: "Find a Job",                   es: "Encontrar trabajo"              }, desc: { fr: "LinkedIn et Indeed",         en: "LinkedIn and Indeed",      es: "LinkedIn e Indeed"          }, urgency: "normal",   time: 90, weight: 15 },
    { id: "license",   label: { fr: "Permis de conduire",               en: "Driver License",               es: "Licencia de conducir"           }, desc: { fr: "Examen DMV",                 en: "DMV exam",                 es: "Examen DMV"                 }, urgency: "normal",   time: 45, weight: 10 },
  ],
  2: [
    { id: "credit_score",        label: { fr: "Credit Score — objectif 700+",     en: "Credit Score — target 700+",     es: "Puntaje de crédito — objetivo 700+"  }, desc: { fr: "Secured credit card",           en: "Secured credit card",         es: "Tarjeta de crédito asegurada"   }, urgency: "high",     time: 30,  weight: 20 },
    { id: "taxes_first",         label: { fr: "Taxes IRS — première déclaration", en: "First IRS tax return",           es: "Primera declaración de impuestos IRS"}, desc: { fr: "Deadline 15 avril chaque année", en: "Deadline April 15 every year",es: "Fecha límite 15 de abril"       }, urgency: "critical", time: 90,  weight: 25 },
    { id: "health_insurance",    label: { fr: "Assurance santé",                  en: "Health Insurance",               es: "Seguro de salud"                     }, desc: { fr: "Marketplace ou employeur",      en: "Marketplace or employer",     es: "Marketplace o empleador"        }, urgency: "high",     time: 60,  weight: 20 },
    { id: "diploma_recognition", label: { fr: "Reconnaissance de diplôme",        en: "Degree recognition",             es: "Reconocimiento de título"            }, desc: { fr: "WES ou ECE evaluation",         en: "WES or ECE evaluation",       es: "Evaluación WES o ECE"           }, urgency: "normal",   time: 90,  weight: 15 },
    { id: "savings_account",     label: { fr: "Compte épargne (Savings)",         en: "Savings Account",                es: "Cuenta de ahorros"                   }, desc: { fr: "Objectif 3 mois de salaire",    en: "Target 3 months salary",      es: "Objetivo 3 meses de salario"    }, urgency: "normal",   time: 60,  weight: 10 },
    { id: "real_id",             label: { fr: "REAL ID — pour prendre l'avion",   en: "REAL ID — for domestic flights", es: "REAL ID — para vuelos domésticos"    }, desc: { fr: "Requis depuis mai 2025",         en: "Required since May 2025",     es: "Requerido desde mayo 2025"      }, urgency: "high",     time: 30,  weight: 10 },
  ],
  3: [
    { id: "buy_house",       label: { fr: "Acheter une maison",              en: "Buy a house",           es: "Comprar una casa"              }, desc: { fr: "Mortgage et down payment",      en: "Mortgage and down payment",   es: "Hipoteca y pago inicial"        }, urgency: "normal",   time: 365, weight: 20 },
    { id: "family_petition", label: { fr: "Faire venir sa famille (I-130)", en: "Bring family (I-130)",  es: "Traer familia (I-130)"         }, desc: { fr: "Petition pour conjoint/enfants", en: "Petition for spouse/children",es: "Petición para cónyuge/hijos"    }, urgency: "normal",   time: 180, weight: 20 },
    { id: "taxes_annual",    label: { fr: "Taxes IRS annuelles ✓",           en: "Annual IRS taxes ✓",    es: "Impuestos IRS anuales ✓"       }, desc: { fr: "Chaque année avant le 15 avril", en: "Every year before April 15",  es: "Cada año antes del 15 de abril" }, urgency: "critical", time: 365, weight: 20 },
    { id: "create_llc",      label: { fr: "Créer son entreprise (LLC)",      en: "Start a business (LLC)",es: "Crear empresa (LLC)"           }, desc: { fr: "Secretary of State",             en: "Secretary of State",          es: "Secretario de Estado"           }, urgency: "normal",   time: 180, weight: 15 },
    { id: "vote_register",   label: { fr: "S'inscrire pour voter",           en: "Register to vote",      es: "Registrarse para votar"        }, desc: { fr: "Droit de vote Green Card",       en: "Green Card voting rights",    es: "Derechos de voto Green Card"    }, urgency: "normal",   time: 90,  weight: 10 },
    { id: "invest",          label: { fr: "Commencer à investir",            en: "Start investing",        es: "Empezar a invertir"            }, desc: { fr: "401k, IRA, ETFs",               en: "401k, IRA, ETFs",             es: "401k, IRA, ETFs"                }, urgency: "normal",   time: 180, weight: 15 },
  ],
  4: [
    { id: "citizenship_eligible", label: { fr: "Vérifier éligibilité N-400",  en: "Check N-400 eligibility",   es: "Verificar elegibilidad N-400" }, desc: { fr: "5 ans de Green Card minimum",   en: "5 years Green Card minimum",  es: "5 años de Green Card mínimo"   }, urgency: "high",     time: 30,  weight: 20 },
    { id: "taxes_annual_4",       label: { fr: "Taxes IRS annuelles ✓",       en: "Annual IRS taxes ✓",        es: "Impuestos IRS anuales ✓"      }, desc: { fr: "Chaque année avant le 15 avril",en: "Every year before April 15",  es: "Cada año antes del 15 de abril"}, urgency: "critical", time: 365, weight: 15 },
    { id: "n400_form",            label: { fr: "Formulaire N-400",            en: "Form N-400",                es: "Formulario N-400"             }, desc: { fr: "Demande de naturalisation",     en: "Naturalization application",  es: "Solicitud de naturalización"   }, urgency: "high",     time: 90,  weight: 20 },
    { id: "civic_test",           label: { fr: "Test civique (100 questions)",en: "Civic test (100 questions)",es: "Test cívico (100 preguntas)"  }, desc: { fr: "Histoire et gouvernement US",   en: "US history and government",   es: "Historia y gobierno de EE.UU." }, urgency: "high",     time: 60,  weight: 20 },
    { id: "oath",                 label: { fr: "Cérémonie du serment",        en: "Oath ceremony",             es: "Ceremonia del juramento"      }, desc: { fr: "Tu deviens citoyen américain !", en: "You become a US citizen!",   es: "¡Te conviertes en ciudadano!"  }, urgency: "normal",   time: 30,  weight: 15 },
    { id: "us_passport",          label: { fr: "Passeport américain",         en: "US Passport",               es: "Pasaporte americano"          }, desc: { fr: "Voyager sans visa",             en: "Travel without visa",         es: "Viajar sin visa"               }, urgency: "normal",   time: 60,  weight: 10 },
  ],
  5: [
    { id: "renew_greencard",    label: { fr: "Renouveler Green Card (I-90)", en: "Renew Green Card (I-90)",   es: "Renovar Green Card (I-90)"    }, desc: { fr: "Tous les 10 ans",               en: "Every 10 years",              es: "Cada 10 años"                  }, urgency: "high",     time: 180, weight: 20 },
    { id: "taxes_lifetime",     label: { fr: "Taxes IRS — chaque année ✓",  en: "IRS taxes — every year ✓", es: "Impuestos IRS — cada año ✓"   }, desc: { fr: "15 avril — sans exception",     en: "April 15 — no exception",     es: "15 de abril — sin excepción"   }, urgency: "critical", time: 365, weight: 25 },
    { id: "renew_passport_us",  label: { fr: "Renouveler passeport US",      en: "Renew US passport",        es: "Renovar pasaporte americano"  }, desc: { fr: "Tous les 10 ans",               en: "Every 10 years",              es: "Cada 10 años"                  }, urgency: "normal",   time: 180, weight: 15 },
    { id: "update_address",     label: { fr: "Mettre à jour adresse USCIS", en: "Update USCIS address",     es: "Actualizar dirección USCIS"   }, desc: { fr: "En cas de déménagement",        en: "When you move",               es: "Cuando te mudes"               }, urgency: "normal",   time: 30,  weight: 10 },
    { id: "community",          label: { fr: "Communauté Kuabo",             en: "Kuabo Community",          es: "Comunidad Kuabo"              }, desc: { fr: "Aide les nouveaux immigrants",  en: "Help new immigrants",         es: "Ayuda a nuevos inmigrantes"    }, urgency: "normal",   time: 0,   weight: 30 },
  ],
};

// ══════════════════════════════════════════════
// STEP GUIDES
// ══════════════════════════════════════════════
export const STEP_GUIDES: Record<string, { guideUrl: string | null; explorerType: string | null; why: Record<Lang, string> }> = {
  ssn:                  { guideUrl: "/guide/ssn",              explorerType: "ssn",   why: { fr: "Le SSN est ton identifiant fiscal aux USA. Sans lui, tu ne peux pas travailler légalement, ouvrir un compte ou louer un appartement.",               en: "The SSN is your tax ID in the USA. Without it, you cannot work legally, open a bank account or rent an apartment.",                          es: "El SSN es tu identificador fiscal en EE.UU. Sin él, no puedes trabajar legalmente, abrir una cuenta bancaria o alquilar." } },
  phone:                { guideUrl: "/guide/phone",            explorerType: null,    why: { fr: "Un numéro US est indispensable pour être contacté par les employeurs, les banques et les services gouvernementaux.",                                   en: "A US number is essential to be contacted by employers, banks and government services.",                                                      es: "Un número de EE.UU. es esencial para ser contactado por empleadores, bancos y servicios gubernamentales." } },
  bank:                 { guideUrl: "/guide/bank",             explorerType: "bank",  why: { fr: "Un compte bancaire US te permet de recevoir ton salaire, payer ton loyer et construire ton credit score.",                                             en: "A US bank account lets you receive your salary, pay rent and build your credit score.",                                                      es: "Una cuenta bancaria de EE.UU. te permite recibir tu salario, pagar el alquiler y construir tu historial crediticio." } },
  greencard:            { guideUrl: "/guide/greencard",        explorerType: "uscis", why: { fr: "Ta Green Card physique est la preuve officielle de ta résidence permanente. Elle est valide 10 ans.",                                                 en: "Your physical Green Card is official proof of your permanent residency. Valid for 10 years.",                                                es: "Tu Green Card física es prueba oficial de tu residencia permanente. Válida por 10 años." } },
  housing:              { guideUrl: "/guide/housing",          explorerType: null,    why: { fr: "Un logement stable est la base de tout. Sans adresse permanente, tu ne peux pas recevoir ton SSN ou ta Green Card.",                                   en: "Stable housing is the foundation of everything. Without a permanent address, you can't receive your SSN or Green Card.",                     es: "Un alojamiento estable es la base de todo. Sin dirección permanente, no puedes recibir tu SSN o Green Card." } },
  job:                  { guideUrl: "/guide/job",              explorerType: null,    why: { fr: "Un emploi te donne un revenu stable et te permet de construire ton credit score.",                                                                    en: "A job gives you stable income and helps build your credit score.",                                                                           es: "Un trabajo te da ingresos estables y te ayuda a construir tu historial crediticio." } },
  license:              { guideUrl: "/guide/license",          explorerType: "dmv",   why: { fr: "Le permis US est aussi une pièce d'identité officielle. Avec le REAL ID tu peux prendre l'avion sans passeport.",                                     en: "The US license is also official ID. With REAL ID you can fly domestically without a passport.",                                             es: "La licencia de EE.UU. también es identificación oficial. Con REAL ID puedes volar sin pasaporte." } },
  credit_score:         { guideUrl: "/guide/credit_score",     explorerType: null,    why: { fr: "Un bon credit score (+700) te permet d'obtenir un appartement, un prêt voiture et de meilleures conditions pour acheter une maison.",                 en: "A good credit score (+700) lets you get an apartment, car loan, and better terms to buy a house.",                                          es: "Un buen puntaje de crédito (+700) te permite obtener apartamento, préstamo de auto y mejores condiciones para comprar casa." } },
  taxes_first:          { guideUrl: "/guide/taxes",            explorerType: null,    why: { fr: "Déclarer tes impôts avant le 15 avril est une obligation légale. Tu peux aussi obtenir des remboursements importants.",                               en: "Filing your taxes before April 15 is a legal obligation. You can also get important refunds.",                                               es: "Declarar tus impuestos antes del 15 de abril es una obligación legal. También puedes obtener reembolsos importantes." } },
  health_insurance:     { guideUrl: "/guide/health_insurance", explorerType: null,    why: { fr: "Une visite aux urgences sans assurance peut coûter des milliers de dollars.",                                                                          en: "An ER visit without insurance can cost thousands of dollars.",                                                                               es: "Una visita a urgencias sin seguro puede costar miles de dólares." } },
  diploma_recognition:  { guideUrl: "/guide/diploma",          explorerType: null,    why: { fr: "Faire reconnaître ton diplôme te permet d'accéder à des emplois qualifiés.",                                                                          en: "Having your degree recognized gives you access to qualified jobs.",                                                                          es: "Reconocer tu título te da acceso a empleos calificados." } },
  savings_account:      { guideUrl: "/guide/savings",          explorerType: null,    why: { fr: "Un compte épargne avec 3 mois de salaire te protège en cas d'urgence.",                                                                               en: "A savings account with 3 months salary protects you in emergencies.",                                                                        es: "Una cuenta de ahorros con 3 meses de salario te protege en emergencias." } },
  real_id:              { guideUrl: "/guide/real_id",          explorerType: "dmv",   why: { fr: "Le REAL ID est obligatoire depuis mai 2025 pour prendre l'avion aux USA.",                                                                            en: "REAL ID is required since May 2025 for domestic flights in the USA.",                                                                        es: "El REAL ID es obligatorio desde mayo de 2025 para vuelos domésticos en EE.UU." } },
  buy_house:            { guideUrl: "/guide/buy_house",        explorerType: null,    why: { fr: "Acheter une maison est le meilleur investissement aux USA.",                                                                                           en: "Buying a house is the best investment in the USA.",                                                                                          es: "Comprar una casa es la mejor inversión en EE.UU." } },
  family_petition:      { guideUrl: "/guide/family_petition",  explorerType: null,    why: { fr: "Le formulaire I-130 te permet de faire venir ton conjoint, enfants ou parents aux USA légalement.",                                                   en: "Form I-130 lets you bring your spouse, children or parents to the USA legally.",                                                            es: "El formulario I-130 te permite traer a tu cónyuge, hijos o padres a EE.UU. legalmente." } },
  taxes_annual:         { guideUrl: "/guide/taxes",            explorerType: null,    why: { fr: "Les taxes IRS sont dues chaque année avant le 15 avril — sans exception.",                                                                            en: "IRS taxes are due every year before April 15 — no exception.",                                                                              es: "Los impuestos del IRS se deben pagar cada año antes del 15 de abril — sin excepción." } },
  create_llc:           { guideUrl: "/guide/llc",              explorerType: null,    why: { fr: "Créer une LLC te protège personnellement et te donne une crédibilité professionnelle.",                                                               en: "Creating an LLC protects you personally and gives you professional credibility.",                                                            es: "Crear una LLC te protege personalmente y te da credibilidad profesional." } },
  vote_register:        { guideUrl: "/guide/vote",             explorerType: null,    why: { fr: "S'inscrire pour voter te donne une voix dans les décisions politiques qui t'affectent.",                                                              en: "Registering to vote gives you a voice in political decisions that affect you.",                                                              es: "Registrarse para votar te da voz en las decisiones políticas que te afectan." } },
  invest:               { guideUrl: "/guide/invest",           explorerType: null,    why: { fr: "Investir tôt dans des ETFs, 401k ou IRA te permet de construire de la richesse à long terme.",                                                        en: "Investing early in ETFs, 401k or IRA lets you build long-term wealth.",                                                                     es: "Invertir temprano en ETFs, 401k o IRA te permite construir riqueza a largo plazo." } },
  citizenship_eligible: { guideUrl: "/guide/citizenship",      explorerType: null,    why: { fr: "Après 5 ans de Green Card tu peux demander la citoyenneté américaine.",                                                                               en: "After 5 years with a Green Card you can apply for US citizenship.",                                                                          es: "Después de 5 años con Green Card puedes solicitar la ciudadanía americana." } },
  taxes_annual_4:       { guideUrl: "/guide/taxes",            explorerType: null,    why: { fr: "Les taxes IRS sont dues chaque année sans exception.",                                                                                                 en: "IRS taxes are due every year without exception.",                                                                                            es: "Los impuestos del IRS se deben pagar cada año sin excepción." } },
  n400_form:            { guideUrl: "/guide/n400",             explorerType: null,    why: { fr: "Le formulaire N-400 est la demande officielle de naturalisation (~$725).",                                                                            en: "Form N-400 is the official naturalization application (~$725).",                                                                             es: "El formulario N-400 es la solicitud oficial de naturalización (~$725)." } },
  civic_test:           { guideUrl: "/guide/civic_test",       explorerType: null,    why: { fr: "Le test civique comporte 100 questions. Tu dois en répondre correctement à 6 sur 10.",                                                               en: "The civic test has 100 questions. You must correctly answer 6 out of 10.",                                                                  es: "El test cívico tiene 100 preguntas. Debes responder correctamente 6 de 10." } },
  oath:                 { guideUrl: "/guide/oath",             explorerType: null,    why: { fr: "La cérémonie du serment est le moment où tu deviens officiellement citoyen américain.",                                                               en: "The oath ceremony is when you officially become a US citizen.",                                                                              es: "La ceremonia del juramento es cuando te conviertes oficialmente en ciudadano americano." } },
  us_passport:          { guideUrl: "/guide/us_passport",      explorerType: null,    why: { fr: "Le passeport américain te permet de voyager dans 186 pays sans visa.",                                                                                en: "The US passport lets you travel to 186 countries without a visa.",                                                                          es: "El pasaporte americano te permite viajar a 186 países sin visa." } },
  renew_greencard:      { guideUrl: "/guide/renew_greencard",  explorerType: "uscis", why: { fr: "Ta Green Card doit être renouvelée tous les 10 ans via le formulaire I-90.",                                                                          en: "Your Green Card must be renewed every 10 years via Form I-90.",                                                                             es: "Tu Green Card debe renovarse cada 10 años mediante el formulario I-90." } },
  taxes_lifetime:       { guideUrl: "/guide/taxes",            explorerType: null,    why: { fr: "Les taxes IRS sont dues chaque année le 15 avril — pour toujours.",                                                                                   en: "IRS taxes are due every year on April 15 — forever.",                                                                                        es: "Los impuestos del IRS se deben pagar cada año el 15 de abril — para siempre." } },
  renew_passport_us:    { guideUrl: "/guide/us_passport",      explorerType: null,    why: { fr: "Le passeport américain doit être renouvelé tous les 10 ans.",                                                                                         en: "The US passport must be renewed every 10 years.",                                                                                           es: "El pasaporte americano debe renovarse cada 10 años." } },
  update_address:       { guideUrl: "/guide/uscis_address",    explorerType: "uscis", why: { fr: "Tu dois signaler tout changement d'adresse à l'USCIS dans les 10 jours (formulaire AR-11).",                                                         en: "You must report any address change to USCIS within 10 days (Form AR-11).",                                                                  es: "Debes reportar cualquier cambio de dirección a USCIS en 10 días (Formulario AR-11)." } },
  community:            { guideUrl: null,                      explorerType: null,    why: { fr: "La communauté Kuabo te connecte avec d'autres immigrants qui ont vécu les mêmes défis.",                                                              en: "The Kuabo community connects you with other immigrants who've faced the same challenges.",                                                   es: "La comunidad Kuabo te conecta con otros inmigrantes que han enfrentado los mismos desafíos." } },
};

// ══════════════════════════════════════════════
// ARMY GUIDE
// ══════════════════════════════════════════════
export const ARMY_GUIDE: Record<string, Record<Lang, { title: string; desc: string; steps: string[]; tip: string }>> = {
  army: {
    fr: { title: "🎖️ Ton parcours Army + DV", desc: "Tu es dans l'US Army avec une DV Lottery. Tu as des avantages uniques.", steps: ["Logement fourni sur la base militaire", "SSN fourni par l'Army dès l'enrôlement", "TRICARE couvre toi et ta famille gratuitement", "Naturalisation possible après 1 an de service actif", "Salaire garanti dès le premier jour"], tip: "Parle au JAG Officer (avocat militaire gratuit) pour toutes tes questions légales." },
    en: { title: "🎖️ Your Army + DV Journey",  desc: "You're in the US Army with a DV Lottery. You have unique advantages.",    steps: ["Housing provided on base", "SSN provided by the Army upon enlistment", "TRICARE covers you and your family for free", "Citizenship possible after 1 year of active duty", "Salary guaranteed from day one"],             tip: "Talk to your JAG Officer (free military lawyer) for all your legal questions." },
    es: { title: "🎖️ Tu camino Army + DV",     desc: "Estás en el US Army con una DV Lottery. Tienes ventajas únicas.",        steps: ["Alojamiento en la base militar", "SSN proporcionado por el Army al alistarte", "TRICARE te cubre a ti y a tu familia gratis", "Ciudadanía posible después de 1 año de servicio activo", "Salario garantizado desde el primer día"], tip: "Habla con el JAG Officer (abogado militar gratuito) para tus preguntas legales." },
  },
  army_interest: {
    fr: { title: "🤔 Rejoindre l'Army avec une DV", desc: "Voilà comment t'engager dans l'US Army avec ton statut DV.", steps: ["Va sur goarmy.com ou trouve un recruteur", "Tu dois avoir 17-35 ans et parler anglais", "Passe le test ASVAB", "Choisis ta spécialité (MOS)", "Commence le Boot Camp — 10 semaines"], tip: "L'Army offre la naturalisation accélérée en 1 an — un énorme avantage DV." },
    en: { title: "🤔 Join the Army with a DV",      desc: "Here's how to enlist in the US Army with your DV status.",           steps: ["Go to goarmy.com or find a recruiter", "You must be 17-35 and speak English", "Take the ASVAB test", "Choose your specialty (MOS)", "Start Boot Camp — 10 weeks"],                   tip: "The Army offers fast-track naturalization in 1 year — a huge DV advantage." },
    es: { title: "🤔 Unirse al Army con una DV",    desc: "Así es como alistarte en el US Army con tu estatus DV.",             steps: ["Ve a goarmy.com o encuentra un reclutador", "Debes tener 17-35 años y hablar inglés", "Toma el examen ASVAB", "Elige tu especialidad (MOS)", "Comienza el Boot Camp — 10 semanas"],           tip: "El Army ofrece naturalización acelerada en 1 año — una enorme ventaja DV." },
  },
  army_unsure: {
    fr: { title: "❓ Army — les infos clés",  desc: "Tu hésites encore. Voilà ce que tu dois savoir.", steps: ["L'Army accepte les détenteurs de DV Lottery", "Tu gardes tes droits de résident permanent", "Naturalisation accélérée disponible après 1 an", "Tu peux refuser et continuer ton parcours DV classique", "Prends le temps de décider sans pression"], tip: "Tu peux changer d'avis plus tard. Kuabo sera là pour t'aider." },
    en: { title: "❓ Army — key information", desc: "You're still undecided. Here's what you need to know.",  steps: ["The Army accepts DV Lottery holders", "You keep your permanent resident rights", "Fast-track naturalization available after 1 year", "You can decline and continue your classic DV path", "Take your time to decide without pressure"],        tip: "You can change your mind later. Kuabo will be here to help you." },
    es: { title: "❓ Army — información clave",desc: "Todavía estás indeciso. Esto es lo que necesitas saber.", steps: ["El Army acepta titulares de DV Lottery", "Conservas tus derechos de residente permanente", "Naturalización acelerada disponible después de 1 año", "Puedes declinar y continuar tu camino DV clásico", "Tómate tu tiempo para decidir sin presión"], tip: "Puedes cambiar de opinión más tarde. Kuabo estará aquí para ayudarte." },
  },
};

// ══════════════════════════════════════════════
// BADGES
// ══════════════════════════════════════════════
export const BADGES: Record<string, { emoji: string; label: Record<Lang, string> }> = {
  ssn:          { emoji: "🪪", label: { fr: "SSN",     en: "SSN",      es: "SSN"         } },
  phone:        { emoji: "📱", label: { fr: "Connecté",en: "Connected",es: "Conectado"   } },
  bank:         { emoji: "🏦", label: { fr: "Banque",  en: "Bank",     es: "Banco"       } },
  greencard:    { emoji: "💳", label: { fr: "Résident",en: "Resident", es: "Residente"   } },
  housing:      { emoji: "🏠", label: { fr: "Logement",en: "Home",     es: "Hogar"       } },
  job:          { emoji: "💼", label: { fr: "Emploi",  en: "Job",      es: "Trabajo"     } },
  license:      { emoji: "🚗", label: { fr: "Permis",  en: "License",  es: "Licencia"    } },
  credit_score: { emoji: "📈", label: { fr: "Crédit",  en: "Credit",   es: "Crédito"     } },
  taxes_first:  { emoji: "📊", label: { fr: "Taxes ✓", en: "Taxes ✓",  es: "Impuestos ✓" } },
  n400_form:    { emoji: "🇺🇸", label: { fr: "N-400",  en: "N-400",    es: "N-400"       } },
  oath:         { emoji: "🤝", label: { fr: "Citoyen", en: "Citizen",  es: "Ciudadano"   } },
};

// ══════════════════════════════════════════════
// SEARCH INDEX
// ══════════════════════════════════════════════
export const SEARCH_INDEX = [
  { id: "ssn",       keywords: ["ssn","social","securite","security","seguro","numero","number","número"],                    label: { fr: "Numéro de Sécurité Sociale (SSN)", en: "Social Security Number (SSN)", es: "Número de Seguro Social (SSN)"     }, url: "/guide/ssn",              emoji: "🪪", phase: 1 },
  { id: "phone",     keywords: ["phone","sim","telephone","télé","mobile","mint","tmobile","t-mobile"],                      label: { fr: "Carte SIM / Téléphone US",         en: "SIM Card / US Phone",          es: "SIM / Teléfono US"                 }, url: "/guide/phone",            emoji: "📱", phase: 1 },
  { id: "bank",      keywords: ["bank","banque","banco","chase","compte","account","argent"],                                label: { fr: "Compte Bancaire",                  en: "Bank Account",                 es: "Cuenta Bancaria"                   }, url: "/guide/bank",             emoji: "🏦", phase: 1 },
  { id: "greencard", keywords: ["green","card","greencard","carte","residence","residencia","uscis"],                        label: { fr: "Green Card physique",              en: "Physical Green Card",          es: "Green Card física"                 }, url: "/guide/greencard",        emoji: "💳", phase: 1 },
  { id: "housing",   keywords: ["housing","logement","maison","house","appartement","apartment","loyer"],                   label: { fr: "Logement permanent",               en: "Permanent Housing",            es: "Vivienda permanente"               }, url: "/guide/housing",          emoji: "🏠", phase: 1 },
  { id: "job",       keywords: ["job","emploi","trabajo","linkedin","indeed","travail","work"],                              label: { fr: "Trouver un emploi",                en: "Find a Job",                   es: "Encontrar trabajo"                 }, url: "/guide/job",              emoji: "💼", phase: 1 },
  { id: "license",   keywords: ["license","permis","licencia","dmv","conduire","drive","voiture"],                          label: { fr: "Permis de conduire",               en: "Driver License",               es: "Licencia de conducir"              }, url: "/guide/license",          emoji: "🚗", phase: 1 },
  { id: "credit",    keywords: ["credit","score","credito","crédit","carte","card","700"],                                   label: { fr: "Credit Score",                     en: "Credit Score",                 es: "Puntaje de Crédito"                }, url: "/guide/credit_score",     emoji: "📈", phase: 2 },
  { id: "taxes",     keywords: ["taxes","impots","impôts","irs","april","avril","w2","w-2","1040"],                         label: { fr: "Taxes IRS",                        en: "IRS Taxes",                    es: "Impuestos IRS"                     }, url: "/guide/taxes",            emoji: "📊", phase: 2 },
  { id: "health",    keywords: ["health","sante","santé","salud","assurance","insurance","medicaid","hmo"],                 label: { fr: "Assurance Santé",                  en: "Health Insurance",             es: "Seguro de Salud"                   }, url: "/guide/health_insurance", emoji: "🏥", phase: 2 },
  { id: "diploma",   keywords: ["diploma","diplome","diplôme","wes","ece","degree","titre","estudios"],                     label: { fr: "Reconnaissance de Diplôme",        en: "Degree Recognition",           es: "Reconocimiento de Título"          }, url: "/guide/diploma",          emoji: "🎓", phase: 2 },
  { id: "savings",   keywords: ["savings","epargne","épargne","ahorro","hysa","ally","marcus","vanguard"],                  label: { fr: "Compte Épargne",                   en: "Savings Account",              es: "Cuenta de Ahorros"                 }, url: "/guide/savings",          emoji: "💰", phase: 2 },
  { id: "realid",    keywords: ["real","id","realid","avion","avión","plane","flight","star","etoile"],                     label: { fr: "REAL ID",                          en: "REAL ID",                      es: "REAL ID"                           }, url: "/guide/real_id",          emoji: "🪪", phase: 2 },
  { id: "house",     keywords: ["maison","house","buy","acheter","comprar","mortgage","hypotheque"],                        label: { fr: "Acheter une Maison",               en: "Buy a House",                  es: "Comprar una Casa"                  }, url: "/guide/buy_house",        emoji: "🏡", phase: 3 },
  { id: "family",    keywords: ["family","famille","familia","i130","i-130","conjoint","spouse","petition"],                label: { fr: "Faire venir sa Famille (I-130)",   en: "Bring Family (I-130)",         es: "Traer a la Familia (I-130)"         }, url: "/guide/family_petition",  emoji: "👨‍👩‍👧", phase: 3 },
  { id: "llc",       keywords: ["llc","entreprise","company","empresa","business","ein","secretary"],                       label: { fr: "Créer une LLC",                    en: "Create an LLC",                es: "Crear una LLC"                     }, url: "/guide/llc",              emoji: "🏢", phase: 3 },
  { id: "vote",      keywords: ["vote","voter","votar","election","citoyen","citizen","register"],                          label: { fr: "S'inscrire pour Voter",            en: "Register to Vote",             es: "Registrarse para Votar"            }, url: "/guide/vote",             emoji: "🗳️", phase: 3 },
  { id: "invest",    keywords: ["invest","investir","invertir","etf","401k","ira","roth","bourse"],                         label: { fr: "Commencer à Investir",             en: "Start Investing",              es: "Empezar a Invertir"                }, url: "/guide/invest",           emoji: "📈", phase: 3 },
  { id: "citizen",   keywords: ["citoyennete","citoyenneté","citizenship","ciudadania","ciudadanía","n400","naturalisation"],label: { fr: "Citoyenneté / N-400",              en: "Citizenship / N-400",          es: "Ciudadanía / N-400"                }, url: "/guide/n400",             emoji: "🇺🇸", phase: 4 },
  { id: "civictest", keywords: ["civic","test","civique","civico","100","questions","histoire","history"],                  label: { fr: "Test Civique",                     en: "Civic Test",                   es: "Test Cívico"                       }, url: "/guide/civic_test",       emoji: "📚", phase: 4 },
  { id: "oath",      keywords: ["oath","serment","juramento","ceremony","ceremonie","citoyen"],                             label: { fr: "Cérémonie du Serment",             en: "Oath Ceremony",                es: "Ceremonia del Juramento"           }, url: "/guide/oath",             emoji: "🤝", phase: 4 },
  { id: "passport",  keywords: ["passport","passeport","pasaporte","us","americain","américain"],                          label: { fr: "Passeport Américain",              en: "US Passport",                  es: "Pasaporte Americano"               }, url: "/guide/us_passport",      emoji: "🛂", phase: 4 },
  { id: "renew",     keywords: ["renew","renouveler","renovar","i90","i-90","10","ans","years"],                            label: { fr: "Renouveler Green Card (I-90)",     en: "Renew Green Card (I-90)",      es: "Renovar Green Card (I-90)"         }, url: "/guide/renew_greencard",  emoji: "💳", phase: 5 },
];
